spring:
  application:
    name: fruit-color-extractor-service
  config:
    import: optional:configserver:http://localhost:8888  
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
